# Generated by Django 3.2.2 on 2021-05-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_tag_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(related_name="articles", to="articles.Tag"),
        ),
    ]
